[package]
name = "advent-of-code-2023"
version = "0.1.0"
authors = ["Max Davidson <davidsonmax@gmail.com>"]
edition = "2021"
license = "MIT"

[lib]
doctest = false

[dependencies]
bit-set = "^0.5.0"
itertools = "^0.12.0"
num = "^0.4.0"
regex = "^1.10.0"
