on: [push]

name: CI

env:
  RUSTFLAGS: --codegen target-cpu=native

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Get Rust config
        run: echo RUST_CFG=$(cargo --quiet rustc -- --print cfg) >> $GITHUB_ENV

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --release --color=always -- --color=always
